import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import {
  fitSvgTextLines,
  validateBmcPlantUmlLayout,
  validateBmcSvgLayout,
} from "../scripts/lib/bmc-visual-layout.mjs";

const svgPath = "docs/product/bmc/source/derived/datacanvas-bmc.svg";
const plantUmlPath = "docs/product/bmc/source/derived/datacanvas-bmc.puml";
const readmePath = "docs/product/bmc/README.md";

test("BMC README is a clickable human navigation page with visual previews", () => {
  const readme = fs.readFileSync(readmePath, "utf8");
  assert.match(readme, /\[[^\]]+\]\(bmc-v0\.2\.md\)/u);
  assert.match(readme, /!\[[^\]]+\]\(source\/derived\/datacanvas-bmc\.svg\)/u);
  assert.match(readme, /!\[[^\]]+\]\(source\/derived\/datacanvas-bmc\.png\)/u);
  assert.match(
    readme,
    /\[!\[[^\]]+\]\(source\/derived\/datacanvas-bmc\.png\)\]\(source\/derived\/datacanvas-bmc\.pdf\)/u,
  );
  assert.match(readme, /\[[^\]]+\]\(source\/derived\/datacanvas-bmc\.puml\)/u);
  assert.doesNotMatch(readme, /`docs\/product\/bmc\//u);
  assert.doesNotMatch(readme, /## Команды|validation-needs\.json/u);
});

test("committed BMC SVG keeps text inside balanced frames", () => {
  const svg = fs.readFileSync(svgPath, "utf8");
  const issues = validateBmcSvgLayout(svg);
  assert.deepEqual(issues, []);
  assert.doesNotMatch(svg, /data-role="bmc-(?:subtitle|footer)"/);
});

test("BMC SVG rejects visible generator service text", () => {
  const svg = fs.readFileSync(svgPath, "utf8").replace(
    "</svg>",
    '<text data-role="bmc-footer">SVG является каноническим визуальным источником</text>\n</svg>',
  );
  const issues = validateBmcSvgLayout(svg);
  assert.ok(issues.some((issue) => issue.includes("service")));
});

test("BMC SVG layout rejects text below a frame", () => {
  const svg = fs.readFileSync(svgPath, "utf8").replace(/(<tspan x="42" y=")\d+("[^>]*>)/, "$19999$2");
  const issues = validateBmcSvgLayout(svg);
  assert.ok(issues.some((issue) => issue.includes("exceeds vertical frame bounds")));
});

test("BMC SVG layout rejects an uneven grid gap", () => {
  const svg = fs.readFileSync(svgPath, "utf8").replace(
    'data-block="B2" data-layout-slot="top-center" transform="translate(1510 280)"',
    'data-block="B2" data-layout-slot="top-center" transform="translate(1520 280)"',
  );
  const issues = validateBmcSvgLayout(svg);
  assert.ok(issues.some((issue) => issue.includes("top-row gaps")));
});

test("BMC SVG layout rejects a title outside the canvas", () => {
  const svg = fs.readFileSync(svgPath, "utf8").replace(
    'data-role="bmc-title" x="174"',
    'data-role="bmc-title" x="3900"',
  );
  const issues = validateBmcSvgLayout(svg);
  assert.ok(issues.some((issue) => issue.includes("title exceeds canvas bounds")));
});

test("BMC SVG layout rejects an inner rectangle outside its block", () => {
  const svg = fs.readFileSync(svgPath, "utf8").replace(
    '<rect width="640" height="16"',
    '<rect width="900" height="16"',
  );
  const issues = validateBmcSvgLayout(svg);
  assert.ok(issues.some((issue) => issue.includes("inner rect exceeds frame bounds")));
});

test("BMC SVG layout rejects a divider outside its block", () => {
  const svg = fs.readFileSync(svgPath, "utf8").replace(
    '<line x1="34" y1="182" x2="606" y2="182"',
    '<line x1="34" y1="182" x2="900" y2="182"',
  );
  const issues = validateBmcSvgLayout(svg);
  assert.ok(issues.some((issue) => issue.includes("inner line exceeds frame bounds")));
});

test("BMC text fitting retries a smaller allowed font for a wide word", () => {
  const layout = fitSvgTextLines(["WWWWWWWW"], {
    maxWidth: 220,
    startY: 40,
    maxY: 160,
    maxFontSize: 40,
    minFontSize: 24,
  });
  assert.ok(layout.fontSize < 40);
  assert.ok(layout.fontSize >= 24);
});

test("committed BMC PlantUML keeps bounded labels and a complete grid", () => {
  const source = fs.readFileSync(plantUmlPath, "utf8");
  const issues = validateBmcPlantUmlLayout(source);
  assert.deepEqual(issues, []);
  assert.doesNotMatch(source, /generated by|do not edit by hand/iu);
});

test("BMC PlantUML rejects generator service comments", () => {
  const source = fs.readFileSync(plantUmlPath, "utf8").replace(
    "@startuml\n",
    "@startuml\n' generated by a service; do not edit by hand.\n",
  );
  const issues = validateBmcPlantUmlLayout(source);
  assert.ok(issues.some((issue) => issue.includes("service comments")));
});

test("BMC PlantUML layout rejects an overlong label line", () => {
  const source = fs.readFileSync(plantUmlPath, "utf8");
  const oversized = source.replace(
    "<b>8. Ключевые партнеры</b>",
    `<b>8. ${"Очень длинная строка ".repeat(8).trim()}</b>`,
  );
  const issues = validateBmcPlantUmlLayout(oversized);
  assert.ok(issues.some((issue) => issue.includes("label line exceeds")));
});

test("BMC PlantUML layout rejects a missing vertical grid relation", () => {
  const source = fs.readFileSync(plantUmlPath, "utf8");
  const issues = validateBmcPlantUmlLayout(source.replace("B43 -[hidden]down- E2\n", ""));
  assert.ok(issues.some((issue) => issue.includes("B43 -[hidden]down- E2")));
});

test("BMC PlantUML layout rejects business content under the wrong alias", () => {
  const source = fs.readFileSync(plantUmlPath, "utf8")
    .replace(" as B2 #", " as SWAP #")
    .replace(" as B1 #", " as B2 #")
    .replace(" as SWAP #", " as B1 #");
  const issues = validateBmcPlantUmlLayout(source);
  assert.ok(issues.some((issue) => issue.includes("B2 must contain business blocks 2")));
});
